### ISSUE TITLE
[Build question] Export template settings

### ISSUE THREAD

**Issue by Inglonias** [qrrk/Catapult#20]
This isn't really a bug report; more a question on your export settings for Godot.

While doing the work for the changelog I noticed that there were some graphical oddities. Most notably, whenever the Stable/Experimental radio buttons were disabled, they would also get much bigger than they otherwise would be. This behavior persisted even after I exported the project to run on another computer. My export also did not include the unzip util that yours did.
I suspect these issues are down to my own inexperience with the engine and editor.

It might be a good idea to share your Godot export templates in the repo to assist other contributors. This is obviously not a terribly urgent request by any means.

**Comment by qrrk** [comment]
> Most notably, whenever the Stable/Experimental radio buttons were disabled, they would also get much bigger than they otherwise would be.

I've also noticed this in Godot 3.4. Must be due to some changes in theming. I myself am still on 3.3.4, so it's not an issue for me. I am putting off the transition to 3.4 for another day.

> My export also did not include the unzip util that yours did.

This is what I do to include it (as well as some other stuff). On Linux, it's all the same minus the `utils` folder.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/19731636/146605725-6ad37fc9-8791-4d72-9c24-29f981370d16.png">

> It might be a good idea to share your Godot export templates in the repo to assist other contributors.

Maybe, but I don't think there is a way to share export settings conveniently. I would have to be a list of verbal directions.
