### ISSUE TITLE
Linux: compiling confusion

### ISSUE THREAD

**Issue by MitztheKat** [qrrk/Catapult#27]
Hi,
This is either an enhancement or needed clarification, but as of right now catapult downloads the files for CBN but is unable to run them, and does not provide any error or notice if the game fails to run.
So, I sit here, confused on why I got the raw files and why I can't figure out how to compile on linux.
It's... a bit confusing... it says it's self-contained, but it shows that it recognises my installation but since it seems completely uncompiled, I'm a bit lost...
_i'm forced to reinstall windows soon so whatever_
This isn't urgent at all, not to mention I'll be out cold for a few hours soon-
but hope you can see to this!

**Comment by qrrk** [comment]
Wow, that's how you know someone is _really_ confused: when he can't even describe the problem coherently.

Sorry, I don't mean to mock you, I'm just having a really hard time following your story. It seems like you're piling multiple issues together.

> This is either an enhancement or needed clarification, but as of right now catapult downloads the files for CBN but is unable to run them, and does not provide any error or notice if the game fails to run.

Does it at least extract the game and show that it is installed? It should be in `<launcher_dir>/bn/current`. If the game files are there, see if the game will run on its own, without the launcher. If the game is not installed, try enabling debug mode in Catapult, maybe it will give some insight into what goes wrong (it will likely be the archive extraction step).

> So, I sit here, confused on why I got the raw files and why I can't figure out how to compile on linux.
It's... a bit confusing... it says it's self-contained, but it shows that it recognises my installation but since it seems completely uncompiled, I'm a bit lost...

This is the most confusing part for me. Sounds like you can run the project in the editor, but aren't sure how to build it? Here's a short guide, from the very beginning, just in case. I need to write one anyway, so might as well do it now.

1. Clone the Catapult repository, or download it by clicking _Code → Download ZIP_ on the GitHub page.
2. Download the Godot engine editor: https://downloads.tuxfamily.org/godotengine/3.3.4/Godot_v3.3.4-stable_x11.64.zip (I'm still using an older release. The latest one causes a couple of minor visual glitches that I haven't addressed yet, but it will also work.)
3. Extract the Godot executable and run it. You will see the Project Manager window. Click _Scan_ and select the directory with Catapult sources. The project will show up on the list.
4. Double-click on the Catapult project to load it into the editor.
5. Go to _Project → Export..._
6. Click _Add..._ and select _Linux/X11_ to add the suitable export preset. If it tells you the export template is missing, click _Manage Export Templates_ and download it.
7. Finally, click _Export Project_.

Let me know if this helps or if misunderstood your problem.
